"""empty message

Revision ID: 1fd559505bca
Revises: cdb4ce4f4ff0
Create Date: 2024-07-06 18:18:13.590977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fd559505bca'
down_revision = 'cdb4ce4f4ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_from_favorite', sa.Integer(), nullable=True),
    sa.Column('user_id_to_favorite', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_from_favorite'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id_to_favorite'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('followers')
    # ### end Alembic commands ###
