"""empty message

Revision ID: cdb4ce4f4ff0
Revises: ba4e45f3d71c
Create Date: 2024-06-09 17:30:59.107121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdb4ce4f4ff0'
down_revision = 'ba4e45f3d71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('palnet_favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('palnet_favorites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name='palnet_favorites_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='palnet_favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='palnet_favorites_pkey')
    )
    op.drop_table('planet_favorites')
    # ### end Alembic commands ###
