"""empty message

Revision ID: e108957e3a74
Revises: 1fd559505bca
Create Date: 2024-07-07 17:59:34.420378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e108957e3a74'
down_revision = '1fd559505bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_home_world_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('characters_specie_id_fkey', type_='foreignkey')
        batch_op.drop_column('home_world_id')
        batch_op.drop_column('specie_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specie_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('home_world_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('characters_specie_id_fkey', 'species', ['specie_id'], ['id'])
        batch_op.create_foreign_key('characters_home_world_id_fkey', 'planets', ['home_world_id'], ['id'])

    # ### end Alembic commands ###
